### ISSUE TITLE
Ensure link correctly leads to repo when transferred.

### ISSUE THREAD

**Issue by irieasha** [Bezjaad/Notification-Link#1]
Test to ensure link correctly leads to repo when transferred.

**Comment by irieasha** [comment]
This is a comment added to the issue after transferring it from ashamoran/Notifications-Link to bezjaad/notifications-link

**Comment by irieasha** [comment]
@ashamoran @bezjaad @IrieAsha Please check links in notifications.

**Comment by ashamoran** [comment]
Closing this issue for further testing.

**Comment by irieasha** [comment]
Reopening to check notification
